### ISSUE TITLE
Legacy TODO from README.md

### ISSUE THREAD

**Issue by rjmurillo** [rjmurillo/moq.analyzers#45]
There are several issues left over from the former maintainer. Each of these should be broken out into a separate sub issue and integrated.

- [ ] Setup() should be used for methods, not for properties
- [ ] AdvancedMatcherAttribute should accept only IMatcher types
- [ ] Checks for protected mocks when dynamically referencing their members
- [ ] Setup() requires overridable members
- [ ] Mock.Get() should not take literals
